#! /bin/sh
# /etc/init.d/hudprojectorcontroller

case "$1" in
  start)
    echo "Starting HUD Projector Controller"
    python /usr/bin/hudprojectorcontroller.py start
    ;;
  stop)
    echo "Stopping HUD Projector Controller"
    python /usr/bin/hudprojectorcontroller.py stop
    ;;
  restart)
    echo "Restarting HUD Projector Controller"
    python /usr/bin/hudprojectorcontroller.py restart
    ;;
  *)
    echo "Usage: /etc/init.d/hudprojectorcontroller{start|stop|restart}"
    exit 1
    ;;
esac

exit 0
