#! /bin/sh
# /etc/init.d/carhud7seg
# defaults 96

case "$1" in
  start)
    echo "Starting CarHUD 7 Segment GUI"
    python /usr/bin/carhud_dual7seg.py &
    ;;
  stop)
    echo "Stopping CarHUD 7 Segment GUI"
    killall `cat /tmp/carhud_dual7seg.pid`
    rm /tmp/carhud_dual7seg.pid
    ;;
  restart)
    echo "Restarting CarHUD 7 Segment GUI"
    killall `cat /tmp/carhud_dual7seg.pid`
    rm /tmp/carhud_dual7seg.pid
    python /usr/bin/carhud_dual7seg.py &
    ;;
  *)
    echo "Usage: /etc/init.d/carhud7seg{start|stop|restart}"
    exit 1
    ;;
esac

exit 0
