#! /bin/sh
# /etc/init.d/carhud7seg-startup-init
#  start 20 1 2 3 4 5 . stop 80 0 6 .

case "$1" in
  start)
    echo "Starting CarHUD 7 Segment Init"
    /usr/bin/carhud_dual7seg_init.sh
    ;;
  stop)
    echo "Stopping CarHUD 7 Segment Init"
    # DO NOTHING HERE BESIDES PRINT
    ;;
  *)
    echo "Usage: /etc/init.d/carhud7seg-startup-init{start|stop}"
    exit 1
    ;;
esac

exit 0
